name: Run tests with coverage

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    tests-with-coverage:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: [ "8.2", "8.3", "8.4" ]
        steps:
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    coverage: xdebug, pcov
                    tools: composer:v2

            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Install Coveralls
                run: composer require --dev -W php-coveralls/php-coveralls:"^2.8.0"

            -   name: Install Dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Check php-coveralls installation
                run: vendor/bin/php-coveralls --version || echo "php-coveralls is not installed"

            -   name: Execute unit tests via PHPUnit with coverage
                run: vendor/bin/phpunit --coverage-clover build/logs/clover-${{ matrix.php-version }}.xml

            -   name: Upload coverage results to Coveralls
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                run: vendor/bin/php-coveralls --coverage_clover=build/logs/clover-${{ matrix.php-version }}.xml -v
